version: '2'
services:
  mongo:
    image: "mongo:latest"
    expose:
    - 27017
    networks:
      - db
  mongo_client:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    networks:
      - db
    depends_on:
      - mongo
  yl24vh_api_dev:
    build:
      context: ../../backend/
      dockerfile: ./docker/dev/Dockerfile
    ports:
     - "1337:1337"
    networks:
      - db
    depends_on:
      - mongo
    volumes:
      - ./../../backend/api:/app/api
      - ./../../backend/config:/app/config
      - ./../../backend/assets:/app/assets
  yl24vh_client_dev:
    build:
      context: ../../front/
      dockerfile: ./docker/dev/Dockerfile
    ports:
     - "3000:3000"
    volumes:
      - ./../../front/src:/app/src
      - ./../../front/public:/app/public

networks:
  db:
   driver: bridge